added DriverDaoJdbcImpl and CarDaoJdbcImpl
Ilya-brinchuk/jv-taxi-service pull request #4
Opened 2021-01-16 21:33 UTC by Ilya-brinchuk

2021-01-17 10:08 UTC, RuslanIbIsh requested changes

2021-01-17 10:08 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                + "FROM service_taxi.cars "
service_taxi если это название бд, то в чеклисте есть об этом упоминание

2021-01-17 10:08 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                + "Where cars.car_id = ? AND cars.deleted = false";
в чек листе есть поминание про удаленный manufacturer

2021-01-17 10:08 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                + "WHERE cars_drivers.driver_id = ? AND cars.deleted = false";
используй псевдонимы "FROM cars_drivers cd"   + "INNER JOIN manufacturers m"
cd.car_id = m.manufacturer_id

2021-01-17 10:08 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                Car car = new Car(model, manufacturer);
в чек листе просят вынести логику в отдельный метод

2021-01-17 10:08 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                Driver driver = new Driver(driverName, driverLicence);
согласно чек листа в отдельный метод просят )))

2021-01-18 13:03 UTC, KseniiaMakarova requested changes

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/GenericDao.java
> +
redundant empty line

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +                                          `drivers_licence` VARCHAR(225) NOT NULL,
there is no need to indicate `driver_` prefix for each column because the columns are located in `drivers` table

same for other column names in manufacturer and car tables

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +    CHANGE COLUMN `driver_id` `driver_id` BIGINT(11) NOT NULL ;
do we need this?

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +                                               `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
this table should not have an id

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +                                               `cars_id` BIGINT(11) NOT NULL,
```suggestion
                                               `car_id` BIGINT(11) NOT NULL,
```

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +    ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT 0 AFTER `cars_id`,
this column also should not be present in this table

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +    DROP COLUMN `deleted`;
let's remove this and add the query that is correct from the start

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +        }
```suggestion
        String query = "INSERT cars (model, manufacturer_id) VALUES (?, ?)";
        try (Connection connection = ConnectionUtil.getConnection();
                PreparedStatement preparedStatement = connection.prepareStatement(query,
                        Statement.RETURN_GENERATED_KEYS)) {
            preparedStatement.setString(1, car.getModel());
            preparedStatement.setLong(2, car.getManufacturer().getId());
            preparedStatement.executeUpdate();
            ResultSet resultSet = preparedStatement.getGeneratedKeys();
            if (resultSet.next()) {
                car.setId(resultSet.getObject(1, Long.class));
            }
        } catch (SQLException e) {
            throw new DataProcessingException("Can't insert car " + car, e);
        }
        addDriversForCar(car);
        return car;
```

don't open one connection inside of another

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +            addDriversForCar(car);
same here

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +            int updateRows = preparedStatement.executeUpdate();
this statement was already executed

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +            deleteDriversForCar(id);
let's not delete data from `cars_drivers` here

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +            for (int i = 0; i < quantityDrivers; i++) {
let's use for each

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +
redundant empty line

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +
same

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                + "Inner join manufacturers "
```suggestion
        String query = "SELECT c.car_id, c.model, c.manufacturer_id,"
                + " m.manufacturer_country, m.manufacturer_name "
                + "FROM cars c "
                + "INNER JOIN manufacturers m "
```
use aliases please

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                car.setDrivers(getDriversFromCar(car.getId()));
don't open a connection inside a connection - move this line out of the try block

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +            return getCars(resultSet);
let's not use the additional private method getCars() here

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                + "WHERE cars_drivers.car_id = ? AND drivers.deleted = false";
let's use aliases everywhere

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                Long driverID = resultSet.getObject("driver_id", Long.class);
```suggestion
                Long driverId = resultSet.getObject("driver_id", Long.class);
```

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +            throw new DataProcessingException("", e);
any informative message here?

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                + " m.manufacturer_name as manufacturer_name "
we should use `as something` when columns have same names in different tables

`"SELECT c.id AS car_id, c.model, m.id AS manufacturer_id...`

here it is redundant

2021-01-18 13:03 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                + "WHERE cd.driver_id = ? AND c.deleted = false";
let’s join `drivers` table as well - we shouldn’t fetch info if the driver is deleted

2021-01-19 07:04 UTC, KseniiaMakarova requested changes

2021-01-19 07:04 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/ManufacturerDaoJdbcImpl.java
> +        String query = "SELECT * FROM manufacturers m WHERE m.id = ? AND m.deleted = false";
```suggestion
        String query = "SELECT * FROM manufacturers WHERE id = ? AND deleted = false";
```

2021-01-19 07:04 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/ManufacturerDaoJdbcImpl.java
> +                + "WHERE m.id = ? AND m.deleted = false";
same in other methods - there is no need for alias if we work in a single table

2021-01-19 07:04 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/ManufacturerDaoJdbcImpl.java
> +        String query = "INSERT manufacturers (name, country)"
INSERT INTO? does it work ok if you skip INTO?
in all insert queries in all 3 dao classes

2021-01-19 07:04 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +                                CONSTRAINT `car_drivers_drivers` FOREIGN KEY (`driver_id`) REFERENCES `drivers` (`id`),
let's create drivers table before we can reference its column

2021-01-19 07:04 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +                addDriversToCar(car);
a new connection is opened inside the method addDriversToCar()

let's not open one connection inside another

2021-01-19 07:04 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +
redundant empty line

2021-01-19 07:04 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +            addDriversToCar(car);
same here - move these 2 lines below the try-catch

2021-01-19 07:04 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +        throw new DataProcessingException("No car with id " + car.getId());
```suggestion
            preparedStatement.setLong(3, car.getId());
            int updateRows = preparedStatement.executeUpdate();
            if (updateRows <= 0) {
                throw new DataProcessingException("No car with id " + car.getId());
            }
        } catch (SQLException e) {
            throw new DataProcessingException("Can't update this car " + car, e);
        }
        deleteDriversFromCar(car.getId());
        addDriversToCar(car);
        return car;
```

2021-01-19 07:59 UTC, Ilya-brinchuk commented on src/main/java/core/basesyntax/dao/impl/ManufacturerDaoJdbcImpl.java
> +        String query = "INSERT manufacturers (name, country)"
в идее у меня так  String query = "INSERT manufacturers (name, country)" .  Не пойму как так получилось. Делаю все в одной ветке.

2021-01-19 11:17 UTC, KseniiaMakarova approved these changes

2021-01-19 11:17 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +        addDriversToCar(car);
add INSERT INTO to the query of the method `addDriversToCar()`

2021-01-19 11:17 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +
redundant empty line

2021-01-19 11:17 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/impl/CarDaoJdbcImpl.java
> +
same

2021-01-19 12:16 UTC, merged