added AuthenticationFilter and page with log in, added new method fin…
Ilya-brinchuk/jv-taxi-service pull request #7
Opened 2021-01-23 18:10 UTC by Ilya-brinchuk

…dByLogin() in DriverDao, added login and password in Driver class.

2021-01-24 11:18 UTC, RuslanIbIsh requested changes

2021-01-24 11:18 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/dao/impl/DriverDaoJdbcImpl.java
> +            preparedStatement.setString(5, driver.getPassword());
тут логика такая - номера это последовательность вопросительных знаков, на третьем месте вопоросителоный знак у login - я ты туда кладешь driver.getId()

2021-01-24 11:18 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/web/filter/AuthenticationFilter.java
> +    private static final Injector injector = Injector.getInstance("core.basesyntax");
injector - наверно лишний

2021-01-24 11:25 UTC, RuslanIbIsh commented on src/main/java/core/basesyntax/web/filter/AuthenticationFilter.java
> +            resp.sendRedirect("/login");
```suggestion
            resp.sendRedirect(req.getContextPath() + "/login");
```

2021-01-24 11:34 UTC, RuslanIbIsh approved these changes

2021-01-25 17:01 UTC, Sofasmile requested changes

2021-01-25 17:01 UTC, Sofasmile commented on src/main/java/core/basesyntax/exception/AuthenticationException.java
> +public class AuthenticationException extends RuntimeException {
```suggestion
public class AuthenticationException extends Exception {
```

2021-01-25 17:01 UTC, Sofasmile commented on src/main/java/core/basesyntax/security/AuthenticationServiceForDriver.java
> +    DriverService driverService;
access modifier?

2021-01-25 17:01 UTC, Sofasmile commented on src/main/java/core/basesyntax/security/AuthenticationServiceForDriver.java
> +        Driver driver = driverService.findByLogin(login)
Read about it in the Slack)

2021-01-25 17:01 UTC, Sofasmile commented on src/main/java/core/basesyntax/web/filter/AuthenticationFilter.java
> +        if (url.equals("/login") || url.equals("/drivers/add")) {
Read about it in the Slack)

2021-01-26 09:12 UTC, Sofasmile approved these changes

2021-01-26 10:24 UTC, merged